### ISSUE TITLE
Request for automatic stream download feature

### ISSUE THREAD

**Issue by talkahe** [sergioalmela/TwitchDownloader#5]
Hello,

I have been testing this repository to download live streams from Twitch and it has been working great for me. However, I was wondering if there is an option to download the stream automatically when it starts. If there isn't, I would like to suggest this feature be added to the repository.

I believe this feature would be beneficial for many users who do not want to miss out on downloading a live stream just because they were not available to start the download manually.

Thank you for your time and consideration.

**Comment by sergioalmela** [comment]
Good request, I will add it to the todo list for the next release.

**Comment by talkahe** [comment]
thank you!

**Comment by talkahe** [comment]
From the terminal it doesn't seem to work, it doesn't detect when the streaming starts.
